name: Test Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      - name: Build With Gradle
        run: |
          chmod +x gradlew
          ./gradlew assembleRelease --build-cache --parallel --warning-mode all

      - name: Prepare App
        run: |
          mkdir -p ${{ github.workspace }}/apk/
          cp -r app/build/outputs/apk/release/*.apk ${{ github.workspace }}/apk/

      - name: Upload App To Artifact
        uses: actions/upload-artifact@v4
        with:
          name: com.github.tvbox.osc
          path: ${{ github.workspace }}/apk
          if-no-files-found: warn
